# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXd_cCpMMeFQbEpqxE2lGiTMbe_hh-IR
"""

from google.colab import files

# Upload CSV file
uploaded = files.upload()

import pandas as pd

# Load the uploaded CSV file into a DataFrame
df = pd.read_csv("heart.csv.csv")

# Display the first 5 rows
df.head()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import joblib

df = pd.read_csv("heart.csv.csv")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nTarget Variable Distribution:")
sns.countplot(data=df, x='condition')
plt.title("Target (condition) Distribution")
plt.show()

X = df.drop(columns='condition')
y = df['condition']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Neural Network': MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)
}

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1-Score': f1_score(y_test, y_pred)
    })
    disp = ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred))
    disp.plot()
    plt.title(name)
    plt.show()

results_df = pd.DataFrame(results)
print(results_df)

best_model = max(models.items(), key=lambda item: f1_score(y_test, item[1].predict(X_test)))[1]
joblib.dump(best_model, "best_heart_model.joblib")
joblib.dump(scaler, "scaler.joblib")

model = joblib.load("best_heart_model.joblib")
scaler = joblib.load("scaler.joblib")

try:
    age = float(input("age (years): "))
    sex = int(input("sex (1 = male, 0 = female): "))
    cp = int(input("chest pain type (0 = typical angina, 1 = atypical angina, 2 = non-anginal, 3 = asymptomatic): "))
    trestbps = float(input("resting blood pressure (90–200 mm Hg): "))
    chol = float(input("cholesterol (mg/dl, 100–600): "))
    fbs = int(input("fasting blood sugar > 120 mg/dl? (1 = yes, 0 = no): "))
    restecg = int(input("resting ECG (0 = normal, 1 = ST-T abnormal, 2 = LV hypertrophy): "))
    thalach = float(input("max heart rate (60–220): "))
    exang = int(input("exercise-induced angina? (1 = yes, 0 = no): "))
    oldpeak = float(input("ST depression (0.0–6.0): "))
    slope = int(input("slope of ST segment (0 = up, 1 = flat, 2 = down): "))
    ca = int(input("number of vessels colored (0–3): "))
    thal = int(input("thal (1 = normal, 2 = fixed defect, 3 = reversible defect): "))

    user_input = np.array([[age, sex, cp, trestbps, chol, fbs, restecg,
                            thalach, exang, oldpeak, slope, ca, thal]])

    user_input_scaled = scaler.transform(user_input)
    result = best_model.predict(user_input_scaled)[0]

    print("\nPrediction complete.")
    if result == 1:
        print("The model predicts: HIGH RISK of Heart Disease")
    else:
        print("The model predicts: LOW RISK of Heart Disease")

except Exception as e:
    print("Invalid input. Please follow the value ranges.")
    print(f"Error: {e}")

sample_input = np.array([[63,1,3,145,233,1,0,150,0,2.3,0,0,1]])
print("Sample input data:", sample_input.tolist())

sample_scaled = scaler.transform(sample_input)
prediction = best_model.predict(sample_scaled)
print("Sample Input Prediction (1 = Disease, 0 = No Disease):", prediction[0])